# ==========================
# MySQL Database Configuration
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/crif_chatbot?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=crif
spring.datasource.password=crif123

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
